In [6]:
import pandas as pd
import numpy as np

df= pd.read_csv("../data/employees.csv")
print("Data shape:",df.shape)
display(df.head())

Data shape: (8, 5)

   id     name department  salary       city
0   1     Arun      Sales   30000    Chennai
1   2    Priya         HR   45000    Chennai
2   3    Rahul         IT   60000  Bangalore
3   4    Divya         IT   75000    Chennai
4   5  Karthik    Finance   90000     Mumbai

In [7]:
df.info()
display(df.describe())
print("MIssing values:\n",df.isna().sum())

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          8 non-null      int64
 1   name        8 non-null      str
 2   department  8 non-null      str
 3   salary      8 non-null      int64
 4   city        8 non-null      str
dtypes: int64(2), str(3)
memory usage: 452.0 bytes

            id        salary
count  8.00000      8.000000
mean   4.50000  58500.000000
std    2.44949  18913.336187
min    1.00000  30000.000000
25%    2.75000  47250.000000
50%    4.50000  56000.000000
75%    6.25000  69750.000000
max    8.00000  90000.000000

MIssing values:
 id            0
name          0
department    0
salary        0
city          0
dtype: int64

In [8]:
# department analysis. employee headcount and average salary for each department

In [9]:
department_summary=(
    df.groupby("department")
    .agg(
        headcount=("id","count"),
        average_salary=("salary","mean"),
        maximum_salary=("salary","max")
    )
    .reset_index()
)

display(department_summary)

  department  headcount  average_salary  maximum_salary
0    Finance          1    90000.000000           90000
1         HR          2    46500.000000           48000
2         IT          3    67666.666667           75000
3      Sales          2    41000.000000           52000

In [10]:
# filtering empolyees earning above 50000 and wroking in chennai

In [11]:
high_earners= df[df["salary"] > 50000]
chennai_employees= df[df["city"] == "Chennai"]
print("high earners:")
display(high_earners)

print("employees in chennai:")
display(chennai_employees)

high earners:

   id     name department  salary       city
2   3    Rahul         IT   60000  Bangalore
3   4    Divya         IT   75000    Chennai
4   5  Karthik    Finance   90000     Mumbai
5   6    Meena      Sales   52000  Bangalore
6   7   Suresh         IT   68000    Chennai

employees in chennai:

   id    name department  salary     city
0   1    Arun      Sales   30000  Chennai
1   2   Priya         HR   45000  Chennai
3   4   Divya         IT   75000  Chennai
6   7  Suresh         IT   68000  Chennai

In [12]:
#performance measurement
#using %timeit magic command

In [14]:
%timeit df.groupby("department")["salary"].mean()

697 μs ± 156 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)